[package]
name = "ora"
version = "0.10.2"
edition = "2021"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ora-client = { version = "0.10.2", path = "../ora-client" }
ora-client-macros = { version = "0.8.1", path = "../ora-client-macros", optional = true }

[features]
default = ["macros"]

macros = ["dep:ora-client-macros"]

[lints]
workspace = true
