[package]
name = "ora-backend"
version = "0.12.4"
edition = "2024"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
uuid.workspace = true

[lints]
workspace = true

[features]
default = ["test"]
test = []
