[package]
name = "ora-e2e"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-stream = "0.3.6"
async-trait.workspace = true
console-subscriber = "0.4.1"
eyre = "0.6.12"
fjall = { version = "2.4.4" }
flume = "0.11.1"
futures.workspace = true
ora = { version = "0.11.0", path = "../ora" }
ora-client = { version = "0.11.0", path = "../ora-client" }
ora-proto = { version = "0.2.0", path = "../ora-proto" }
ora-server = { version = "0.2.0", path = "../ora-server" }
ora-storage = { version = "0.2.0", path = "../ora-storage" }
ora-storage-fjall = { version = "0.2.0", path = "../ora-storage-fjall" }
ora-storage-memory = { version = "0.2.0", path = "../ora-storage-memory" }
ora-storage-sqlite = { version = "0.4.0", path = "../ora-storage-sqlite" }
parking_lot = { version = "0.12.3", features = ["deadlock_detection"] }
rand = "0.8.5"
rusqlite = "0.34.0"
schemars = "0.8.21"
serde = "1.0.216"
tempfile = "3.14.0"
tokio = { version = "1.42.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "tracing",
] }
tonic.workspace = true
tonic-web = "0.12.3"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid.workspace = true

[lints]
workspace = true

[[bench]]
name = "generic"
harness = false
