syntax = "proto3";

package ora.common.v1;

import "google/protobuf/duration.proto";
import "ora/common/v1/job.proto";
import "ora/common/v1/time_range.proto";

// A schedule is a tool for executing jobs at a specific times.
//
// Schedules create new jobs based on various criteria.
message ScheduleDefinition {
  // The timing policy for the schedule.
  ScheduleJobTimingPolicy job_timing_policy = 1;
  // The policy for creating new jobs.
  ScheduleJobCreationPolicy job_creation_policy = 2;
  // The labels of the schedule.
  repeated ScheduleLabel labels = 3;
  // The time range for the schedule.
  //
  // The schedule will not create jobs outside of the time range.
  // If the time range is not provided, the schedule will create jobs
  // indefinitely.
  ora.common.v1.TimeRange time_range = 4;
  // Arbitrary metadata in JSON format.
  optional string metadata_json = 5;
}

message ScheduleJobTimingPolicy {
  // The policy for timing new jobs.
  oneof job_timing {
    // Repeat jobs with a given interval.
    ScheduleJobTimingPolicyRepeat repeat = 1;
    // Repeat jobs with a given cron expression.
    ScheduleJobTimingPolicyCron cron = 2;
  }
}

// Repeat jobs with a given interval.
message ScheduleJobTimingPolicyRepeat {
  // The interval between each job.
  google.protobuf.Duration interval = 1;
  // Whether to immediately create a job
  // when the schedule is created.
  bool immediate = 2;
  // The policy for missed jobs.
  ScheduleMissedTimePolicy missed_time_policy = 3;
}

// Repeat jobs with a given cron expression.
message ScheduleJobTimingPolicyCron {
  // The cron expression for the schedule.
  //
  // The reference implementation uses the cron expression
  // format supported by the `cronexpr` Rust crate (<https://docs.rs/cronexpr/latest/cronexpr/>).
  string cron_expression = 1;
  // Whether to immediately create a job
  // when the schedule is created.
  bool immediate = 2;
  // The policy for missed jobs.
  ScheduleMissedTimePolicy missed_time_policy = 3;
}

// The policy that defines how new jobs are created.
message ScheduleJobCreationPolicy {
  // The policy for creating new jobs.
  oneof job_creation {
    // Create new jobs from a given definition,
    // the target execution time is altered for each job.
    ora.common.v1.JobDefinition job_definition = 1;
  }
}

enum ScheduleMissedTimePolicy {
  // The policy is unspecified.
  SCHEDULE_MISSED_TIME_POLICY_UNSPECIFIED = 0;
  // Skip the missed times.
  SCHEDULE_MISSED_TIME_POLICY_SKIP = 1;
  // Create a job for each missed time.
  SCHEDULE_MISSED_TIME_POLICY_CREATE = 2;
}

// A label for a schedule.
//
// Labels can be used to categorize, filter,
// and group schedules.
//
// Any arbitrary metadata can be stored in a label.
message ScheduleLabel {
  // The key of the label.
  //
  // The key must be unique within the schedule.
  // The handling of duplicate keys is undefined
  // and depends on the implementation.
  string key = 1;
  // The value of the label.
  string value = 2;
}
