syntax = "proto3";

package ora.common.v1;

import "google/protobuf/timestamp.proto";

// A time range.
//
// A time range is a range of time between two points.
//
// The time range is inclusive of the start time and exclusive of the end time.
message TimeRange {
  // The start time of the time range.
  //
  // If not provided, the time range is open-ended.
  google.protobuf.Timestamp start = 1;
  // The end time of the time range.
  //
  // If not provided, the time range is open-ended.
  google.protobuf.Timestamp end = 2;
}
