syntax = "proto3";

package ora.snapshot.v1;

import "google/protobuf/timestamp.proto";
import "ora/common/v1/job.proto";
import "ora/common/v1/schedule.proto";
import "ora/common/v1/time_range.proto";

// A service that provides the ability to export and import
// the state of the system for backup and migration purposes.
//
// Note that the data exported and imported is not guaranteed
// to be compatible across implementations, some systems may
// export only a subset of the data, others may import only
// a subset of the data. This is especially important when
// jobs are being executed during the export and import process.
service SnapshotService {
  // Export all the data of the system.
  rpc Export(ExportRequest) returns (stream ExportResponse);
  // Import the full snapshot of the system.
  //
  // Note that this may overwrite the existing state of the system
  // depending on the implementation.
  rpc Import(stream ImportRequest) returns (ImportResponse);
}

// Request for `Export`.
message ExportRequest {}

// Response for `Export`.
message ExportResponse {
  // The batch of data.
  SnapshotData data = 1;
}

// Request for `Import`.
message ImportRequest {
  // The batch of data.
  SnapshotData data = 1;
}

// Response for `Import`.
message ImportResponse {}

// A batch of data.
message SnapshotData {
  // The jobs in the batch.
  repeated ExportedJob jobs = 1;
  // The job executions in the batch.
  repeated ExportedExecution executions = 2;
  // The schedules in the batch.
  repeated ExportedSchedule schedules = 3;
  // The job types in the batch.
  repeated ExportedJobType job_types = 4;
}

// All data belonging to a job.
message ExportedJob {
  // The ID of the job.
  string id = 1;
  // The ID of the schedule that the job belongs to.
  optional string schedule_id = 2;
  // The time when the job was created.
  google.protobuf.Timestamp created_at = 3;
  // The ID of the job type.
  string job_type_id = 4;
  // The target execution time of the job.
  google.protobuf.Timestamp target_execution_time = 5;
  // The retry policy of the job.
  ora.common.v1.JobRetryPolicy retry_policy = 6;
  // The timeout policy of the job.
  ora.common.v1.JobTimeoutPolicy timeout_policy = 7;
  // The labels of the job.
  repeated ora.common.v1.JobLabel labels = 8;
  // The time when the job was marked as inactive.
  google.protobuf.Timestamp marked_unschedulable_at = 9;
  // The time when the job was cancelled.
  google.protobuf.Timestamp cancelled_at = 10;
  // The input payload of the job.
  string input_payload_json = 11;
  // Arbitrary metadata in JSON format.
  optional string metadata_json = 12;
}

// All data belonging to a job execution.
message ExportedExecution {
  // The ID of the job execution.
  string id = 1;
  // The ID of the job.
  string job_id = 2;
  // The target execution time of the job.
  google.protobuf.Timestamp target_execution_time = 3;
  // The ID of the executor that executed the job.
  optional string executor_id = 4;
  // The time when the job execution was created.
  google.protobuf.Timestamp created_at = 5;
  // The time when the job execution was
  // ready
  google.protobuf.Timestamp ready_at = 6;
  // The time when the job execution was
  // assigned to an executor.
  google.protobuf.Timestamp assigned_at = 7;
  // The time when the job execution was
  // started.
  google.protobuf.Timestamp started_at = 8;
  // The time when the job execution succeeded.
  google.protobuf.Timestamp succeeded_at = 9;
  // The time when the job execution failed.
  google.protobuf.Timestamp failed_at = 10;
  // The output payload of the job.
  optional string output_payload_json = 11;
  // The reason why the job execution failed.
  optional string failure_reason = 12;
}

// All data belonging to a schedule.
message ExportedSchedule {
  // The ID of the schedule.
  string id = 1;
  // The time when the schedule was created.
  google.protobuf.Timestamp created_at = 2;
  // The ID of the job type.
  optional string job_type_id = 3;
  // The labels of the schedule.
  repeated ora.common.v1.ScheduleLabel labels = 4;
  // The time when the schedule was marked as inactive.
  google.protobuf.Timestamp marked_unschedulable_at = 5;
  // The time when the schedule was cancelled.
  google.protobuf.Timestamp cancelled_at = 6;
  // The scheduling policy of the schedule.
  ora.common.v1.ScheduleJobTimingPolicy job_timing_policy = 7;
  // The new job policy of the schedule.
  ora.common.v1.ScheduleJobCreationPolicy job_creation_policy = 8;
  // The time range of the schedule.
  ora.common.v1.TimeRange time_range = 10;
  // Arbitrary metadata in JSON format.
  optional string metadata_json = 11;
}

// All data belonging to a job type.
message ExportedJobType {
  ora.common.v1.JobType job_type = 1;
}
