[package]
name = "ora-client"
version = "0.8.0"
edition = "2021"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ahash = "0.8.11"
async-stream = "0.3.6"
async-trait.workspace = true
cronexpr = "1.1.2"
eyre = "0.6.12"
flume = "0.11.1"
futures.workspace = true
indexmap = "2.7.0"
ora-client-macros = { version = "0.8.0", path = "../ora-client-macros", optional = true }
ora-proto = { version = "0.1.0", path = "../ora-proto" }
parking_lot = "0.12.3"
prost = "0.13.4"
schemars = "0.8.21"
serde = { version = "1.0.216", features = [] }
serde_json = "1.0.133"
thiserror = "2.0.7"
tokio = { version = "1.42.0", features = ["macros"] }
tokio-util = "0.7.13"
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
wgroup = { version = "0.1.0", path = "../wgroup" }

[features]
default = ["macros"]

macros = ["dep:ora-client-macros"]

[lints]
workspace = true
