// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/admin/v1/executions.proto (package ora.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/admin/v1/executions.proto.
 */
export const file_ora_admin_v1_executions: GenFile = /*@__PURE__*/
  fileDesc("Ch1vcmEvYWRtaW4vdjEvZXhlY3V0aW9ucy5wcm90bxIMb3JhLmFkbWluLnYxIssECglFeGVjdXRpb24SCgoCaWQYASABKAkSGAoLZXhlY3V0b3JfaWQYAiABKAlIAIgBARItCgZzdGF0dXMYAyABKA4yHS5vcmEuYWRtaW4udjEuRXhlY3V0aW9uU3RhdHVzEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjMKCnN0YXJ0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAGIAQESNQoMc3VjY2VlZGVkX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgCiAEBEjIKCWZhaWxlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIA4gBARI1CgxjYW5jZWxsZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSASIAQESGAoLb3V0cHV0X2pzb24YCSABKAlIBYgBARIbCg5mYWlsdXJlX3JlYXNvbhgKIAEoCUgGiAEBEjkKFXRhcmdldF9leGVjdXRpb25fdGltZRgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCDgoMX2V4ZWN1dG9yX2lkQg0KC19zdGFydGVkX2F0Qg8KDV9zdWNjZWVkZWRfYXRCDAoKX2ZhaWxlZF9hdEIPCg1fY2FuY2VsbGVkX2F0Qg4KDF9vdXRwdXRfanNvbkIRCg9fZmFpbHVyZV9yZWFzb24q0AEKD0V4ZWN1dGlvblN0YXR1cxIgChxFWEVDVVRJT05fU1RBVFVTX1VOU1BFQ0lGSUVEEAASHAoYRVhFQ1VUSU9OX1NUQVRVU19QRU5ESU5HEAESIAocRVhFQ1VUSU9OX1NUQVRVU19JTl9QUk9HUkVTUxACEh4KGkVYRUNVVElPTl9TVEFUVVNfU1VDQ0VFREVEEAMSGwoXRVhFQ1VUSU9OX1NUQVRVU19GQUlMRUQQBBIeChpFWEVDVVRJT05fU1RBVFVTX0NBTkNFTExFRBAFYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * A job execution.
 *
 * @generated from message ora.admin.v1.Execution
 */
export type Execution = Message<"ora.admin.v1.Execution"> & {
  /**
   * The unique ID of the execution.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The ID of the executor handling the execution.
   *
   * @generated from field: optional string executor_id = 2;
   */
  executorId?: string | undefined;

  /**
   * The status of the execution.
   *
   * @generated from field: ora.admin.v1.ExecutionStatus status = 3;
   */
  status: ExecutionStatus;

  /**
   * The timestamp when the execution was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;

  /**
   * The timestamp when the execution started.
   *
   * @generated from field: optional google.protobuf.Timestamp started_at = 5;
   */
  startedAt?: Timestamp | undefined;

  /**
   * The timestamp when the execution successfully completed.
   *
   * @generated from field: optional google.protobuf.Timestamp succeeded_at = 6;
   */
  succeededAt?: Timestamp | undefined;

  /**
   * The timestamp when the execution failed.
   *
   * @generated from field: optional google.protobuf.Timestamp failed_at = 7;
   */
  failedAt?: Timestamp | undefined;

  /**
   * The timestamp when the execution was cancelled.
   *
   * @generated from field: optional google.protobuf.Timestamp cancelled_at = 8;
   */
  cancelledAt?: Timestamp | undefined;

  /**
   * The output or result of the execution.
   *
   * @generated from field: optional string output_json = 9;
   */
  outputJson?: string | undefined;

  /**
   * The error message if the execution failed or was cancelled.
   *
   * @generated from field: optional string failure_reason = 10;
   */
  failureReason?: string | undefined;

  /**
   * The target time of this execution.
   *
   * This is might differ from the job's target execution time
   * in cases such as when an execution is created as part of
   * a retry of a failed execution.
   *
   * @generated from field: google.protobuf.Timestamp target_execution_time = 11;
   */
  targetExecutionTime?: Timestamp | undefined;
};

/**
 * Describes the message ora.admin.v1.Execution.
 * Use `create(ExecutionSchema)` to create a new message.
 */
export const ExecutionSchema: GenMessage<Execution> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_executions, 0);

/**
 * Status of a job execution.
 *
 * @generated from enum ora.admin.v1.ExecutionStatus
 */
export enum ExecutionStatus {
  /**
   * Unknown status.
   *
   * @generated from enum value: EXECUTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The execution is pending.
   *
   * @generated from enum value: EXECUTION_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The execution is in progress.
   *
   * @generated from enum value: EXECUTION_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * The execution has completed successfully.
   *
   * @generated from enum value: EXECUTION_STATUS_SUCCEEDED = 3;
   */
  SUCCEEDED = 3,

  /**
   * The execution has failed.
   *
   * @generated from enum value: EXECUTION_STATUS_FAILED = 4;
   */
  FAILED = 4,

  /**
   * The execution was cancelled.
   *
   * @generated from enum value: EXECUTION_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,
}

/**
 * Describes the enum ora.admin.v1.ExecutionStatus.
 */
export const ExecutionStatusSchema: GenEnum<ExecutionStatus> = /*@__PURE__*/
  enumDesc(file_ora_admin_v1_executions, 0);

