// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/admin/v1/executors.proto (package ora.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { JobType } from "../../jobs/v1/job_pb";
import { file_ora_jobs_v1_job } from "../../jobs/v1/job_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/admin/v1/executors.proto.
 */
export const file_ora_admin_v1_executors: GenFile = /*@__PURE__*/
  fileDesc("ChxvcmEvYWRtaW4vdjEvZXhlY3V0b3JzLnByb3RvEgxvcmEuYWRtaW4udjEilAEKCEV4ZWN1dG9yEgoKAmlkGAEgASgJEhEKBG5hbWUYAiABKAlIAIgBARIwCgxsYXN0X3NlZW5fYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KBnF1ZXVlcxgEIAMoCzIeLm9yYS5hZG1pbi52MS5FeGVjdXRvckpvYlF1ZXVlQgcKBV9uYW1lIngKEEV4ZWN1dG9ySm9iUXVldWUSJgoIam9iX3R5cGUYASABKAsyFC5vcmEuam9icy52MS5Kb2JUeXBlEiEKGW1heF9jb25jdXJyZW50X2V4ZWN1dGlvbnMYAiABKAQSGQoRYWN0aXZlX2V4ZWN1dGlvbnMYAyABKARiBnByb3RvMw", [file_google_protobuf_timestamp, file_ora_jobs_v1_job]);

/**
 * An executor connected to the Ora server.
 *
 * @generated from message ora.admin.v1.Executor
 */
export type Executor = Message<"ora.admin.v1.Executor"> & {
  /**
   * The ID of the executor.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The name of the executor.
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * The time the executor was last seen.
   *
   * @generated from field: google.protobuf.Timestamp last_seen_at = 3;
   */
  lastSeenAt?: Timestamp | undefined;

  /**
   * Job queues of the executor.
   *
   * @generated from field: repeated ora.admin.v1.ExecutorJobQueue queues = 4;
   */
  queues: ExecutorJobQueue[];
};

/**
 * Describes the message ora.admin.v1.Executor.
 * Use `create(ExecutorSchema)` to create a new message.
 */
export const ExecutorSchema: GenMessage<Executor> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_executors, 0);

/**
 * The job queue of an executor for a specific job type.
 *
 * @generated from message ora.admin.v1.ExecutorJobQueue
 */
export type ExecutorJobQueue = Message<"ora.admin.v1.ExecutorJobQueue"> & {
  /**
   * The job type the queue is for.
   *
   * @generated from field: ora.jobs.v1.JobType job_type = 1;
   */
  jobType?: JobType | undefined;

  /**
   * The maximum amount of concurrent executions allowed for this job type.
   *
   * @generated from field: uint64 max_concurrent_executions = 2;
   */
  maxConcurrentExecutions: bigint;

  /**
   * The amount of active executions in the queue.
   *
   * @generated from field: uint64 active_executions = 3;
   */
  activeExecutions: bigint;
};

/**
 * Describes the message ora.admin.v1.ExecutorJobQueue.
 * Use `create(ExecutorJobQueueSchema)` to create a new message.
 */
export const ExecutorJobQueueSchema: GenMessage<ExecutorJobQueue> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_executors, 1);

