// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/admin/v1/jobs.proto (package ora.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Execution, ExecutionStatus } from "./executions_pb";
import { file_ora_admin_v1_executions } from "./executions_pb";
import type { LabelFilter } from "../../common/v1/label_pb";
import { file_ora_common_v1_label } from "../../common/v1/label_pb";
import type { TimeRange } from "../../common/v1/time_range_pb";
import { file_ora_common_v1_time_range } from "../../common/v1/time_range_pb";
import type { Job as Job$1 } from "../../jobs/v1/job_pb";
import { file_ora_jobs_v1_job } from "../../jobs/v1/job_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/admin/v1/jobs.proto.
 */
export const file_ora_admin_v1_jobs: GenFile = /*@__PURE__*/
  fileDesc("ChdvcmEvYWRtaW4vdjEvam9icy5wcm90bxIMb3JhLmFkbWluLnYxIrcBCgNKb2ISCgoCaWQYASABKAkSHQoDam9iGAIgASgLMhAub3JhLmpvYnMudjEuSm9iEhgKC3NjaGVkdWxlX2lkGAMgASgJSACIAQESLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoKZXhlY3V0aW9ucxgFIAMoCzIXLm9yYS5hZG1pbi52MS5FeGVjdXRpb25CDgoMX3NjaGVkdWxlX2lkIs8DCgpKb2JGaWx0ZXJzEg8KB2pvYl9pZHMYASADKAkSFAoMam9iX3R5cGVfaWRzGAIgAygJEhQKDHNjaGVkdWxlX2lkcxgDIAMoCRIUCgxleGVjdXRvcl9pZHMYBCADKAkSFQoNZXhlY3V0aW9uX2lkcxgFIAMoCRI5ChJleGVjdXRpb25fc3RhdHVzZXMYBiADKA4yHS5vcmEuYWRtaW4udjEuRXhlY3V0aW9uU3RhdHVzEjwKFXRhcmdldF9leGVjdXRpb25fdGltZRgHIAEoCzIYLm9yYS5jb21tb24udjEuVGltZVJhbmdlSACIAQESMQoKY3JlYXRlZF9hdBgIIAEoCzIYLm9yYS5jb21tb24udjEuVGltZVJhbmdlSAGIAQESKgoGbGFiZWxzGAkgAygLMhoub3JhLmNvbW1vbi52MS5MYWJlbEZpbHRlchIZCgxtaW5fcHJpb3JpdHkYCiABKAVIAogBARIZCgxtYXhfcHJpb3JpdHkYCyABKAVIA4gBAUIYChZfdGFyZ2V0X2V4ZWN1dGlvbl90aW1lQg0KC19jcmVhdGVkX2F0Qg8KDV9taW5fcHJpb3JpdHlCDwoNX21heF9wcmlvcml0eSqFAgoKSm9iT3JkZXJCeRIcChhKT0JfT1JERVJfQllfVU5TUEVDSUZJRUQQABIfChtKT0JfT1JERVJfQllfQ1JFQVRFRF9BVF9BU0MQARIgChxKT0JfT1JERVJfQllfQ1JFQVRFRF9BVF9ERVNDEAISKgomSk9CX09SREVSX0JZX1RBUkdFVF9FWEVDVVRJT05fVElNRV9BU0MQAxIrCidKT0JfT1JERVJfQllfVEFSR0VUX0VYRUNVVElPTl9USU1FX0RFU0MQBBIdChlKT0JfT1JERVJfQllfUFJJT1JJVFlfQVNDEAUSHgoaSk9CX09SREVSX0JZX1BSSU9SSVRZX0RFU0MQBmIGcHJvdG8z", [file_google_protobuf_timestamp, file_ora_admin_v1_executions, file_ora_common_v1_label, file_ora_common_v1_time_range, file_ora_jobs_v1_job]);

/**
 * Details of a job.
 *
 * @generated from message ora.admin.v1.Job
 */
export type Job = Message<"ora.admin.v1.Job"> & {
  /**
   * The unique ID of the job.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The job definition.
   *
   * @generated from field: ora.jobs.v1.Job job = 2;
   */
  job?: Job$1 | undefined;

  /**
   * A schedule associated with the job (if any).
   *
   * @generated from field: optional string schedule_id = 3;
   */
  scheduleId?: string | undefined;

  /**
   * The timestamp when the job was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp | undefined;

  /**
   * The executions of the job.
   *
   * @generated from field: repeated ora.admin.v1.Execution executions = 5;
   */
  executions: Execution[];
};

/**
 * Describes the message ora.admin.v1.Job.
 * Use `create(JobSchema)` to create a new message.
 */
export const JobSchema: GenMessage<Job> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_jobs, 0);

/**
 * Filters for listing jobs.
 *
 * @generated from message ora.admin.v1.JobFilters
 */
export type JobFilters = Message<"ora.admin.v1.JobFilters"> & {
  /**
   * Filter by job IDs.
   *
   * @generated from field: repeated string job_ids = 1;
   */
  jobIds: string[];

  /**
   * Filter by job type IDs.
   *
   * @generated from field: repeated string job_type_ids = 2;
   */
  jobTypeIds: string[];

  /**
   * Filter by schedule IDs.
   *
   * @generated from field: repeated string schedule_ids = 3;
   */
  scheduleIds: string[];

  /**
   * Filter by executor IDs.
   *
   * @generated from field: repeated string executor_ids = 4;
   */
  executorIds: string[];

  /**
   * Filter by execution IDs.
   *
   * @generated from field: repeated string execution_ids = 5;
   */
  executionIds: string[];

  /**
   * Filter by the status of the last execution.
   *
   * @generated from field: repeated ora.admin.v1.ExecutionStatus execution_statuses = 6;
   */
  executionStatuses: ExecutionStatus[];

  /**
   * Filter by target execution times.
   *
   * The range can be open-ended in either direction.
   *
   * @generated from field: optional ora.common.v1.TimeRange target_execution_time = 7;
   */
  targetExecutionTime?: TimeRange | undefined;

  /**
   * Filter by creation time.
   *
   * The range can be open-ended in either direction.
   *
   * @generated from field: optional ora.common.v1.TimeRange created_at = 8;
   */
  createdAt?: TimeRange | undefined;

  /**
   * Filter by labels.
   *
   * @generated from field: repeated ora.common.v1.LabelFilter labels = 9;
   */
  labels: LabelFilter[];

  /**
   * Filter by minimum priority (inclusive).
   *
   * @generated from field: optional int32 min_priority = 10;
   */
  minPriority?: number | undefined;

  /**
   * Filter by maximum priority (inclusive).
   *
   * @generated from field: optional int32 max_priority = 11;
   */
  maxPriority?: number | undefined;
};

/**
 * Describes the message ora.admin.v1.JobFilters.
 * Use `create(JobFiltersSchema)` to create a new message.
 */
export const JobFiltersSchema: GenMessage<JobFilters> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_jobs, 1);

/**
 * Ordering options for listing jobs.
 *
 * @generated from enum ora.admin.v1.JobOrderBy
 */
export enum JobOrderBy {
  /**
   * Default ordering (by creation time descending).
   *
   * @generated from enum value: JOB_ORDER_BY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Order by creation time ascending.
   *
   * @generated from enum value: JOB_ORDER_BY_CREATED_AT_ASC = 1;
   */
  CREATED_AT_ASC = 1,

  /**
   * Order by creation time descending.
   *
   * @generated from enum value: JOB_ORDER_BY_CREATED_AT_DESC = 2;
   */
  CREATED_AT_DESC = 2,

  /**
   * Order by target execution time ascending.
   *
   * @generated from enum value: JOB_ORDER_BY_TARGET_EXECUTION_TIME_ASC = 3;
   */
  TARGET_EXECUTION_TIME_ASC = 3,

  /**
   * Order by target execution time descending.
   *
   * @generated from enum value: JOB_ORDER_BY_TARGET_EXECUTION_TIME_DESC = 4;
   */
  TARGET_EXECUTION_TIME_DESC = 4,

  /**
   * Order by priority ascending.
   *
   * @generated from enum value: JOB_ORDER_BY_PRIORITY_ASC = 5;
   */
  PRIORITY_ASC = 5,

  /**
   * Order by priority descending.
   *
   * @generated from enum value: JOB_ORDER_BY_PRIORITY_DESC = 6;
   */
  PRIORITY_DESC = 6,
}

/**
 * Describes the enum ora.admin.v1.JobOrderBy.
 */
export const JobOrderBySchema: GenEnum<JobOrderBy> = /*@__PURE__*/
  enumDesc(file_ora_admin_v1_jobs, 0);

