// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/admin/v1/pagination.proto (package ora.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/admin/v1/pagination.proto.
 */
export const file_ora_admin_v1_pagination: GenFile = /*@__PURE__*/
  fileDesc("Ch1vcmEvYWRtaW4vdjEvcGFnaW5hdGlvbi5wcm90bxIMb3JhLmFkbWluLnYxIlgKEVBhZ2luYXRpb25PcHRpb25zEhEKCXBhZ2Vfc2l6ZRgBIAEoDRIcCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAlIAIgBAUISChBfbmV4dF9wYWdlX3Rva2VuYgZwcm90bzM");

/**
 * Pagination options for listing requests.
 *
 * @generated from message ora.admin.v1.PaginationOptions
 */
export type PaginationOptions = Message<"ora.admin.v1.PaginationOptions"> & {
  /**
   * The maximum number of items to return.
   *
   * @generated from field: uint32 page_size = 1;
   */
  pageSize: number;

  /**
   * The token for the next page of results
   * from a previous request (if any).
   *
   * Any filters and ordering applied
   * in the previous request must be identical
   * to those in the current request.
   * In case of mismatch the behavior is unspecified.
   *
   * @generated from field: optional string next_page_token = 2;
   */
  nextPageToken?: string | undefined;
};

/**
 * Describes the message ora.admin.v1.PaginationOptions.
 * Use `create(PaginationOptionsSchema)` to create a new message.
 */
export const PaginationOptionsSchema: GenMessage<PaginationOptions> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_pagination, 0);

