// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/admin/v1/schedules.proto (package ora.admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { LabelFilter } from "../../common/v1/label_pb";
import { file_ora_common_v1_label } from "../../common/v1/label_pb";
import type { TimeRange } from "../../common/v1/time_range_pb";
import { file_ora_common_v1_time_range } from "../../common/v1/time_range_pb";
import type { Schedule as Schedule$1 } from "../../schedules/v1/schedule_pb";
import { file_ora_schedules_v1_schedule } from "../../schedules/v1/schedule_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/admin/v1/schedules.proto.
 */
export const file_ora_admin_v1_schedules: GenFile = /*@__PURE__*/
  fileDesc("ChxvcmEvYWRtaW4vdjEvc2NoZWR1bGVzLnByb3RvEgxvcmEuYWRtaW4udjEi5gEKCFNjaGVkdWxlEgoKAmlkGAEgASgJEiwKCHNjaGVkdWxlGAIgASgLMhoub3JhLnNjaGVkdWxlcy52MS5TY2hlZHVsZRIuCgpjcmVhdGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIsCgZzdGF0dXMYBCABKA4yHC5vcmEuYWRtaW4udjEuU2NoZWR1bGVTdGF0dXMSMwoKc3RvcHBlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAIgBAUINCgtfc3RvcHBlZF9hdCLbAQoPU2NoZWR1bGVGaWx0ZXJzEhQKDHNjaGVkdWxlX2lkcxgBIAMoCRIUCgxqb2JfdHlwZV9pZHMYAiADKAkSLgoIc3RhdHVzZXMYAyADKA4yHC5vcmEuYWRtaW4udjEuU2NoZWR1bGVTdGF0dXMSMQoKY3JlYXRlZF9hdBgEIAEoCzIYLm9yYS5jb21tb24udjEuVGltZVJhbmdlSACIAQESKgoGbGFiZWxzGAUgAygLMhoub3JhLmNvbW1vbi52MS5MYWJlbEZpbHRlckINCgtfY3JlYXRlZF9hdCpqCg5TY2hlZHVsZVN0YXR1cxIfChtTQ0hFRFVMRV9TVEFUVVNfVU5TUEVDSUZJRUQQABIaChZTQ0hFRFVMRV9TVEFUVVNfQUNUSVZFEAESGwoXU0NIRURVTEVfU1RBVFVTX1NUT1BQRUQQAiqBAQoPU2NoZWR1bGVPcmRlckJ5EiEKHVNDSEVEVUxFX09SREVSX0JZX1VOU1BFQ0lGSUVEEAASJAogU0NIRURVTEVfT1JERVJfQllfQ1JFQVRFRF9BVF9BU0MQARIlCiFTQ0hFRFVMRV9PUkRFUl9CWV9DUkVBVEVEX0FUX0RFU0MQAmIGcHJvdG8z", [file_google_protobuf_timestamp, file_ora_common_v1_label, file_ora_common_v1_time_range, file_ora_schedules_v1_schedule]);

/**
 * Schedule details.
 *
 * @generated from message ora.admin.v1.Schedule
 */
export type Schedule = Message<"ora.admin.v1.Schedule"> & {
  /**
   * The unique ID of the schedule.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The schedule definition.
   *
   * @generated from field: ora.schedules.v1.Schedule schedule = 2;
   */
  schedule?: Schedule$1 | undefined;

  /**
   * The timestamp when the schedule was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp | undefined;

  /**
   * The status of the schedule.
   *
   * @generated from field: ora.admin.v1.ScheduleStatus status = 4;
   */
  status: ScheduleStatus;

  /**
   * The timestamp when the schedule was stopped (if any).
   *
   * @generated from field: optional google.protobuf.Timestamp stopped_at = 5;
   */
  stoppedAt?: Timestamp | undefined;
};

/**
 * Describes the message ora.admin.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema: GenMessage<Schedule> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_schedules, 0);

/**
 * Filters for listing schedules.
 *
 * @generated from message ora.admin.v1.ScheduleFilters
 */
export type ScheduleFilters = Message<"ora.admin.v1.ScheduleFilters"> & {
  /**
   * Filter by schedule IDs.
   *
   * @generated from field: repeated string schedule_ids = 1;
   */
  scheduleIds: string[];

  /**
   * Filter by job type IDs.
   *
   * @generated from field: repeated string job_type_ids = 2;
   */
  jobTypeIds: string[];

  /**
   * Filter by status.
   *
   * @generated from field: repeated ora.admin.v1.ScheduleStatus statuses = 3;
   */
  statuses: ScheduleStatus[];

  /**
   * Filter by creation time.
   *
   * The range can be open-ended in either direction.
   *
   * @generated from field: optional ora.common.v1.TimeRange created_at = 4;
   */
  createdAt?: TimeRange | undefined;

  /**
   * Filter by labels.
   *
   * @generated from field: repeated ora.common.v1.LabelFilter labels = 5;
   */
  labels: LabelFilter[];
};

/**
 * Describes the message ora.admin.v1.ScheduleFilters.
 * Use `create(ScheduleFiltersSchema)` to create a new message.
 */
export const ScheduleFiltersSchema: GenMessage<ScheduleFilters> = /*@__PURE__*/
  messageDesc(file_ora_admin_v1_schedules, 1);

/**
 * The status of a schedule.
 *
 * @generated from enum ora.admin.v1.ScheduleStatus
 */
export enum ScheduleStatus {
  /**
   * Unknown status.
   *
   * @generated from enum value: SCHEDULE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The schedule is active.
   *
   * @generated from enum value: SCHEDULE_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * The schedule was stopped.
   *
   * Once a schedule is stopped, it cannot be re-activated.
   *
   * @generated from enum value: SCHEDULE_STATUS_STOPPED = 2;
   */
  STOPPED = 2,
}

/**
 * Describes the enum ora.admin.v1.ScheduleStatus.
 */
export const ScheduleStatusSchema: GenEnum<ScheduleStatus> = /*@__PURE__*/
  enumDesc(file_ora_admin_v1_schedules, 0);

/**
 * Ordering options for listing schedules.
 *
 * @generated from enum ora.admin.v1.ScheduleOrderBy
 */
export enum ScheduleOrderBy {
  /**
   * Unspecified ordering.
   *
   * @generated from enum value: SCHEDULE_ORDER_BY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Order by creation time.
   *
   * @generated from enum value: SCHEDULE_ORDER_BY_CREATED_AT_ASC = 1;
   */
  CREATED_AT_ASC = 1,

  /**
   * Order by creation time, descending.
   *
   * @generated from enum value: SCHEDULE_ORDER_BY_CREATED_AT_DESC = 2;
   */
  CREATED_AT_DESC = 2,
}

/**
 * Describes the enum ora.admin.v1.ScheduleOrderBy.
 */
export const ScheduleOrderBySchema: GenEnum<ScheduleOrderBy> = /*@__PURE__*/
  enumDesc(file_ora_admin_v1_schedules, 1);

