[package]
name = "ora-macros"
version = "0.12.6"
edition = "2021"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[lints]
workspace = true
