[package]
name = "ora-server"
version = "0.12.7"
edition = "2024"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flume = "0.12.0"
futures.workspace = true
ora-backend = { version = "0.12.7", path = "../ora-backend" }
wgroup = { version = "0.1.0", path = "../wgroup" }
prost.workspace = true
prost-types.workspace = true
tonic-prost.workspace = true
tonic = { version = "0.14.2", default-features = false, features = ["codegen"] }
uuid.workspace = true
tokio = { version = "1.49.0", features = ["rt", "macros", "time"] }
tracing.workspace = true
rand = "0.10.0"
serde = "1.0.228"
serde_json = "1.0.148"
tracing-futures = { version = "0.2.5", features = ["futures-03"] }
async-broadcast = "0.7.2"
async-stream = "0.3.6"
jiff = "0.2.18"
cronexpr = "1.4.0"
either = "1.15.0"

[lints]
workspace = true
