// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/jobs/v1/job.proto (package ora.jobs.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Label } from "../../common/v1/label_pb";
import { file_ora_common_v1_label } from "../../common/v1/label_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/jobs/v1/job.proto.
 */
export const file_ora_jobs_v1_job: GenFile = /*@__PURE__*/
  fileDesc("ChVvcmEvam9icy92MS9qb2IucHJvdG8SC29yYS5qb2JzLnYxIq0BCgdKb2JUeXBlEgoKAmlkGAEgASgJEhgKC2Rlc2NyaXB0aW9uGAMgASgJSACIAQESHgoRaW5wdXRfc2NoZW1hX2pzb24YBCABKAlIAYgBARIfChJvdXRwdXRfc2NoZW1hX2pzb24YBSABKAlIAogBAUIOCgxfZGVzY3JpcHRpb25CFAoSX2lucHV0X3NjaGVtYV9qc29uQhUKE19vdXRwdXRfc2NoZW1hX2pzb24i+wEKA0pvYhITCgtqb2JfdHlwZV9pZBgBIAEoCRI5ChV0YXJnZXRfZXhlY3V0aW9uX3RpbWUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhoKEmlucHV0X3BheWxvYWRfanNvbhgDIAEoCRIkCgZsYWJlbHMYBCADKAsyFC5vcmEuY29tbW9uLnYxLkxhYmVsEjIKDnRpbWVvdXRfcG9saWN5GAUgASgLMhoub3JhLmpvYnMudjEuVGltZW91dFBvbGljeRIuCgxyZXRyeV9wb2xpY3kYBiABKAsyGC5vcmEuam9icy52MS5SZXRyeVBvbGljeSJsCg1UaW1lb3V0UG9saWN5EioKB3RpbWVvdXQYASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SLwoJYmFzZV90aW1lGAIgASgOMhwub3JhLmpvYnMudjEuVGltZW91dEJhc2VUaW1lIuIBCgtSZXRyeVBvbGljeRIPCgdyZXRyaWVzGAEgASgEEjMKEGJhY2tvZmZfZHVyYXRpb24YAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SPAoUbWF4X2JhY2tvZmZfZHVyYXRpb24YAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25IAIgBARI2ChBiYWNrb2ZmX3N0cmF0ZWd5GAQgASgOMhwub3JhLmpvYnMudjEuQmFja29mZlN0cmF0ZWd5QhcKFV9tYXhfYmFja29mZl9kdXJhdGlvbiqDAQoPVGltZW91dEJhc2VUaW1lEiEKHVRJTUVPVVRfQkFTRV9USU1FX1VOU1BFQ0lGSUVEEAASKwonVElNRU9VVF9CQVNFX1RJTUVfVEFSR0VUX0VYRUNVVElPTl9USU1FEAESIAocVElNRU9VVF9CQVNFX1RJTUVfU1RBUlRfVElNRRACKnEKD0JhY2tvZmZTdHJhdGVneRIgChxCQUNLT0ZGX1NUUkFURUdZX1VOU1BFQ0lGSUVEEAASGgoWQkFDS09GRl9TVFJBVEVHWV9GSVhFRBABEiAKHEJBQ0tPRkZfU1RSQVRFR1lfRVhQT05FTlRJQUwQAmIGcHJvdG8z", [file_google_protobuf_duration, file_google_protobuf_timestamp, file_ora_common_v1_label]);

/**
 * Definition of a job type.
 *
 * @generated from message ora.jobs.v1.JobType
 */
export type JobType = Message<"ora.jobs.v1.JobType"> & {
  /**
   * The ID of the job type.
   *
   * The ID must only contain ASCII letters (a-z, A-Z), digits (0-9), and underscores.
   * It must start with an ASCII letter (a-z, A-Z).
   *
   * Examples of valid job IDs: "MyJob", "MyJob123", "send_email", "data_backup"
   *
   * Optionally the ID can be prefixed with one or more namespaces
   * separated by dots. Each namespace must follow the same rules as the ID.
   *
   * Examples of valid namespaced job IDs: "com.example.SendEmail", "org.myorg.jobs.MyJob", "data_service.CreateBackup"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The description of the job type.
   *
   * @generated from field: optional string description = 3;
   */
  description?: string | undefined;

  /**
   * The input JSON schema of the job type.
   *
   * @generated from field: optional string input_schema_json = 4;
   */
  inputSchemaJson?: string | undefined;

  /**
   * The output JSON schema of the job type.
   *
   * @generated from field: optional string output_schema_json = 5;
   */
  outputSchemaJson?: string | undefined;
};

/**
 * Describes the message ora.jobs.v1.JobType.
 * Use `create(JobTypeSchema)` to create a new message.
 */
export const JobTypeSchema: GenMessage<JobType> = /*@__PURE__*/
  messageDesc(file_ora_jobs_v1_job, 0);

/**
 * Definition of a job.
 *
 * @generated from message ora.jobs.v1.Job
 */
export type Job = Message<"ora.jobs.v1.Job"> & {
  /**
   * The ID of the job type.
   *
   * @generated from field: string job_type_id = 1;
   */
  jobTypeId: string;

  /**
   * The target execution time of the job.
   *
   * @generated from field: google.protobuf.Timestamp target_execution_time = 2;
   */
  targetExecutionTime?: Timestamp | undefined;

  /**
   * The job input payload JSON that is passed to the executor.
   *
   * @generated from field: string input_payload_json = 3;
   */
  inputPayloadJson: string;

  /**
   * The labels of the job.
   *
   * @generated from field: repeated ora.common.v1.Label labels = 4;
   */
  labels: Label[];

  /**
   * The timeout policy of the job.
   *
   * @generated from field: ora.jobs.v1.TimeoutPolicy timeout_policy = 5;
   */
  timeoutPolicy?: TimeoutPolicy | undefined;

  /**
   * Retry policy for the job.
   *
   * @generated from field: ora.jobs.v1.RetryPolicy retry_policy = 6;
   */
  retryPolicy?: RetryPolicy | undefined;
};

/**
 * Describes the message ora.jobs.v1.Job.
 * Use `create(JobSchema)` to create a new message.
 */
export const JobSchema: GenMessage<Job> = /*@__PURE__*/
  messageDesc(file_ora_jobs_v1_job, 1);

/**
 * Timeout policy for a job.
 *
 * @generated from message ora.jobs.v1.TimeoutPolicy
 */
export type TimeoutPolicy = Message<"ora.jobs.v1.TimeoutPolicy"> & {
  /**
   * The timeout for the job.
   *
   * @generated from field: google.protobuf.Duration timeout = 1;
   */
  timeout?: Duration | undefined;

  /**
   * The base time for the timeout.
   *
   * The timeout is calculated from this time.
   *
   * @generated from field: ora.jobs.v1.TimeoutBaseTime base_time = 2;
   */
  baseTime: TimeoutBaseTime;
};

/**
 * Describes the message ora.jobs.v1.TimeoutPolicy.
 * Use `create(TimeoutPolicySchema)` to create a new message.
 */
export const TimeoutPolicySchema: GenMessage<TimeoutPolicy> = /*@__PURE__*/
  messageDesc(file_ora_jobs_v1_job, 2);

/**
 * Retry policy for a job.
 *
 * @generated from message ora.jobs.v1.RetryPolicy
 */
export type RetryPolicy = Message<"ora.jobs.v1.RetryPolicy"> & {
  /**
   * The number of retries for the job.
   *
   * If the number of retries is zero, the job is not retried.
   *
   * @generated from field: uint64 retries = 1;
   */
  retries: bigint;

  /**
   * The backoff duration between retries.
   *
   * By default, the backoff duration is zero,
   * which means that the job is retried immediately after a failure.
   *
   * @generated from field: google.protobuf.Duration backoff_duration = 2;
   */
  backoffDuration?: Duration | undefined;

  /**
   * The maximum backoff duration between retries.
   *
   * If the backoff duration is greater than the maximum backoff duration,
   * the backoff duration is capped at the maximum backoff duration.
   *
   * This option is only applicable when the backoff strategy is exponential.
   *
   * @generated from field: optional google.protobuf.Duration max_backoff_duration = 3;
   */
  maxBackoffDuration?: Duration | undefined;

  /**
   * The backoff strategy for retries.
   *
   * @generated from field: ora.jobs.v1.BackoffStrategy backoff_strategy = 4;
   */
  backoffStrategy: BackoffStrategy;
};

/**
 * Describes the message ora.jobs.v1.RetryPolicy.
 * Use `create(RetryPolicySchema)` to create a new message.
 */
export const RetryPolicySchema: GenMessage<RetryPolicy> = /*@__PURE__*/
  messageDesc(file_ora_jobs_v1_job, 3);

/**
 * The base time for the timeout.
 *
 * @generated from enum ora.jobs.v1.TimeoutBaseTime
 */
export enum TimeoutBaseTime {
  /**
   * The base time is unspecified and depends on the implementation.
   *
   * @generated from enum value: TIMEOUT_BASE_TIME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The base time is the target execution time of the job.
   *
   * Note that if the target execution time is not set,
   * the timeout is calculated from the start time of the job.
   *
   * If the target execution time is in the past,
   * the jobs may be immediately timed out.
   *
   * @generated from enum value: TIMEOUT_BASE_TIME_TARGET_EXECUTION_TIME = 1;
   */
  TARGET_EXECUTION_TIME = 1,

  /**
   * The base time is the start time of the job.
   *
   * @generated from enum value: TIMEOUT_BASE_TIME_START_TIME = 2;
   */
  START_TIME = 2,
}

/**
 * Describes the enum ora.jobs.v1.TimeoutBaseTime.
 */
export const TimeoutBaseTimeSchema: GenEnum<TimeoutBaseTime> = /*@__PURE__*/
  enumDesc(file_ora_jobs_v1_job, 0);

/**
 * The backoff strategy for retries.
 *
 * @generated from enum ora.jobs.v1.BackoffStrategy
 */
export enum BackoffStrategy {
  /**
   * The backoff strategy is unspecified and depends on the implementation.
   *
   * @generated from enum value: BACKOFF_STRATEGY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The backoff strategy is fixed, which means that the backoff duration is constant between retries.
   *
   * @generated from enum value: BACKOFF_STRATEGY_FIXED = 1;
   */
  FIXED = 1,

  /**
   * The backoff strategy is exponential, which means that the backoff duration increases exponentially between retries.
   *
   * @generated from enum value: BACKOFF_STRATEGY_EXPONENTIAL = 2;
   */
  EXPONENTIAL = 2,
}

/**
 * Describes the enum ora.jobs.v1.BackoffStrategy.
 */
export const BackoffStrategySchema: GenEnum<BackoffStrategy> = /*@__PURE__*/
  enumDesc(file_ora_jobs_v1_job, 1);

