[package]
name = "ora-storage-sqlite"
version = "0.4.0"
edition = "2021"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
deadpool = { version = "0.12.2", default-features = false, features = [
    "unmanaged",
] }
eyre = "0.6.12"
futures.workspace = true
ora-proto = { version = "0.2.0", path = "../ora-proto" }
ora-storage = { version = "0.2.0", path = "../ora-storage" }
parking_lot = "0.12.3"
rkyv = { version = "0.8.9", features = ["indexmap-2", "unaligned", "uuid-1"] }
rusqlite = { version = "0.34.0", features = ["bundled", "uuid"] }
sea-query = { version = "0.32.1", default-features = false, features = [
    "backend-sqlite",
    "with-uuid",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.44.1", features = ["rt"] }
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
