[package]
name = "ora-backend-postgres"
version = "0.12.4"
edition = "2024"
publish.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
__dump_sql = []

[dependencies]
async-stream = "0.3.6"
base64 = "0.22.1"
deadpool-postgres = "0.14.1"
futures.workspace = true
ora-backend = { version = "0.12.4", path = "../ora-backend" }
refinery = { version = "0.9.0", features = ["tokio-postgres"] }
sea-query = { version = "1.0.0-rc.29", default-features = false, features = [
    "backend-postgres",
    "with-uuid",
    "postgres-array",
] }
sea-query-postgres = { version = "0.6.0-rc.3", features = [
    "postgres-array",
    "with-uuid",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["time", "macros"] }
tokio-postgres = { version = "0.7.15", features = ["with-uuid-1"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
ora-backend = { version = "0.12.4", path = "../ora-backend", features = ["test"] }

[lints]
workspace = true
