// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file ora/schedules/v1/schedule.proto (package ora.schedules.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Label } from "../../common/v1/label_pb";
import { file_ora_common_v1_label } from "../../common/v1/label_pb";
import type { TimeRange } from "../../common/v1/time_range_pb";
import { file_ora_common_v1_time_range } from "../../common/v1/time_range_pb";
import type { Job } from "../../jobs/v1/job_pb";
import { file_ora_jobs_v1_job } from "../../jobs/v1/job_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ora/schedules/v1/schedule.proto.
 */
export const file_ora_schedules_v1_schedule: GenFile = /*@__PURE__*/
  fileDesc("Ch9vcmEvc2NoZWR1bGVzL3YxL3NjaGVkdWxlLnByb3RvEhBvcmEuc2NoZWR1bGVzLnYxIr4BCghTY2hlZHVsZRI2CgpzY2hlZHVsaW5nGAEgASgLMiIub3JhLnNjaGVkdWxlcy52MS5TY2hlZHVsaW5nUG9saWN5EiYKDGpvYl90ZW1wbGF0ZRgCIAEoCzIQLm9yYS5qb2JzLnYxLkpvYhIkCgZsYWJlbHMYAyADKAsyFC5vcmEuY29tbW9uLnYxLkxhYmVsEiwKCnRpbWVfcmFuZ2UYBCABKAsyGC5vcmEuY29tbW9uLnYxLlRpbWVSYW5nZSKUAQoQU2NoZWR1bGluZ1BvbGljeRI+CghpbnRlcnZhbBgBIAEoCzIqLm9yYS5zY2hlZHVsZXMudjEuU2NoZWR1bGluZ1BvbGljeUludGVydmFsSAASNgoEY3JvbhgCIAEoCzImLm9yYS5zY2hlZHVsZXMudjEuU2NoZWR1bGluZ1BvbGljeUNyb25IAEIICgZwb2xpY3kimgEKGFNjaGVkdWxpbmdQb2xpY3lJbnRlcnZhbBIrCghpbnRlcnZhbBgBIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIRCglpbW1lZGlhdGUYAiABKAgSPgoSbWlzc2VkX3RpbWVfcG9saWN5GAMgASgOMiIub3JhLnNjaGVkdWxlcy52MS5NaXNzZWRUaW1lUG9saWN5IoIBChRTY2hlZHVsaW5nUG9saWN5Q3JvbhIXCg9jcm9uX2V4cHJlc3Npb24YASABKAkSEQoJaW1tZWRpYXRlGAIgASgIEj4KEm1pc3NlZF90aW1lX3BvbGljeRgDIAEoDjIiLm9yYS5zY2hlZHVsZXMudjEuTWlzc2VkVGltZVBvbGljeSpyChBNaXNzZWRUaW1lUG9saWN5EiIKHk1JU1NFRF9USU1FX1BPTElDWV9VTlNQRUNJRklFRBAAEhsKF01JU1NFRF9USU1FX1BPTElDWV9TS0lQEAESHQoZTUlTU0VEX1RJTUVfUE9MSUNZX0NSRUFURRACYgZwcm90bzM", [file_google_protobuf_duration, file_ora_common_v1_label, file_ora_common_v1_time_range, file_ora_jobs_v1_job]);

/**
 * A schedule is a tool for executing jobs at a specific times.
 *
 * Schedules create new jobs based on various criteria.
 *
 * @generated from message ora.schedules.v1.Schedule
 */
export type Schedule = Message<"ora.schedules.v1.Schedule"> & {
  /**
   * The repeat policy for the schedule.
   *
   * @generated from field: ora.schedules.v1.SchedulingPolicy scheduling = 1;
   */
  scheduling?: SchedulingPolicy | undefined;

  /**
   * The job to be used as a template
   * when creating new jobs.
   *
   * @generated from field: ora.jobs.v1.Job job_template = 2;
   */
  jobTemplate?: Job | undefined;

  /**
   * The labels of the schedule.
   *
   * @generated from field: repeated ora.common.v1.Label labels = 3;
   */
  labels: Label[];

  /**
   * The time range for the schedule.
   *
   * The schedule will not create jobs outside of the time range.
   * If the time range is not provided, the schedule will create jobs
   * indefinitely.
   *
   * @generated from field: ora.common.v1.TimeRange time_range = 4;
   */
  timeRange?: TimeRange | undefined;
};

/**
 * Describes the message ora.schedules.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export const ScheduleSchema: GenMessage<Schedule> = /*@__PURE__*/
  messageDesc(file_ora_schedules_v1_schedule, 0);

/**
 * @generated from message ora.schedules.v1.SchedulingPolicy
 */
export type SchedulingPolicy = Message<"ora.schedules.v1.SchedulingPolicy"> & {
  /**
   * The policy for repeating jobs.
   *
   * @generated from oneof ora.schedules.v1.SchedulingPolicy.policy
   */
  policy: {
    /**
     * Repeat jobs with a given interval.
     *
     * @generated from field: ora.schedules.v1.SchedulingPolicyInterval interval = 1;
     */
    value: SchedulingPolicyInterval;
    case: "interval";
  } | {
    /**
     * Repeat jobs according to a cron expression.
     *
     * @generated from field: ora.schedules.v1.SchedulingPolicyCron cron = 2;
     */
    value: SchedulingPolicyCron;
    case: "cron";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ora.schedules.v1.SchedulingPolicy.
 * Use `create(SchedulingPolicySchema)` to create a new message.
 */
export const SchedulingPolicySchema: GenMessage<SchedulingPolicy> = /*@__PURE__*/
  messageDesc(file_ora_schedules_v1_schedule, 1);

/**
 * Repeat jobs with a given interval.
 *
 * @generated from message ora.schedules.v1.SchedulingPolicyInterval
 */
export type SchedulingPolicyInterval = Message<"ora.schedules.v1.SchedulingPolicyInterval"> & {
  /**
   * The interval between each job.
   *
   * @generated from field: google.protobuf.Duration interval = 1;
   */
  interval?: Duration | undefined;

  /**
   * Whether to immediately create a job
   * when the schedule is created.
   *
   * @generated from field: bool immediate = 2;
   */
  immediate: boolean;

  /**
   * The policy for missed jobs.
   *
   * @generated from field: ora.schedules.v1.MissedTimePolicy missed_time_policy = 3;
   */
  missedTimePolicy: MissedTimePolicy;
};

/**
 * Describes the message ora.schedules.v1.SchedulingPolicyInterval.
 * Use `create(SchedulingPolicyIntervalSchema)` to create a new message.
 */
export const SchedulingPolicyIntervalSchema: GenMessage<SchedulingPolicyInterval> = /*@__PURE__*/
  messageDesc(file_ora_schedules_v1_schedule, 2);

/**
 * Repeat jobs according to a cron expression.
 *
 * @generated from message ora.schedules.v1.SchedulingPolicyCron
 */
export type SchedulingPolicyCron = Message<"ora.schedules.v1.SchedulingPolicyCron"> & {
  /**
   * The cron expression for the schedule.
   *
   * The reference implementation uses the cron expression
   * format supported by the `cronexpr` Rust crate (<https://docs.rs/cronexpr/latest/cronexpr/>).
   *
   * @generated from field: string cron_expression = 1;
   */
  cronExpression: string;

  /**
   * Whether to immediately create a job
   * when the schedule is created.
   *
   * @generated from field: bool immediate = 2;
   */
  immediate: boolean;

  /**
   * The policy for missed jobs.
   *
   * @generated from field: ora.schedules.v1.MissedTimePolicy missed_time_policy = 3;
   */
  missedTimePolicy: MissedTimePolicy;
};

/**
 * Describes the message ora.schedules.v1.SchedulingPolicyCron.
 * Use `create(SchedulingPolicyCronSchema)` to create a new message.
 */
export const SchedulingPolicyCronSchema: GenMessage<SchedulingPolicyCron> = /*@__PURE__*/
  messageDesc(file_ora_schedules_v1_schedule, 3);

/**
 * @generated from enum ora.schedules.v1.MissedTimePolicy
 */
export enum MissedTimePolicy {
  /**
   * The policy is unspecified.
   *
   * @generated from enum value: MISSED_TIME_POLICY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Skip the missed times.
   *
   * @generated from enum value: MISSED_TIME_POLICY_SKIP = 1;
   */
  SKIP = 1,

  /**
   * Create a job for each missed time.
   *
   * @generated from enum value: MISSED_TIME_POLICY_CREATE = 2;
   */
  CREATE = 2,
}

/**
 * Describes the enum ora.schedules.v1.MissedTimePolicy.
 */
export const MissedTimePolicySchema: GenEnum<MissedTimePolicy> = /*@__PURE__*/
  enumDesc(file_ora_schedules_v1_schedule, 0);

