/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CopyableId: typeof import('./src/components/CopyableId.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DurationInput: typeof import('./src/components/DurationInput.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JobDefinitionForm: typeof import('./src/components/JobDefinitionForm.vue')['default']
    JobFilters: typeof import('./src/components/JobFilters.vue')['default']
    JobsTable: typeof import('./src/components/JobsTable.vue')['default']
    JsonEditor: typeof import('./src/components/JsonEditor.vue')['default']
    LabelChip: typeof import('./src/components/LabelChip.vue')['default']
    LabelFilterInput: typeof import('./src/components/LabelFilterInput.vue')['default']
    LabelList: typeof import('./src/components/LabelList.vue')['default']
    LabelsInput: typeof import('./src/components/LabelsInput.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    LoadStatus: typeof import('./src/components/LoadStatus.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RefreshControl: typeof import('./src/components/RefreshControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleDefinitionForm: typeof import('./src/components/ScheduleDefinitionForm.vue')['default']
    ScheduleFilters: typeof import('./src/components/ScheduleFilters.vue')['default']
    SchedulesTable: typeof import('./src/components/SchedulesTable.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    StatNumber: typeof import('./src/components/StatNumber.vue')['default']
    StopSchedulesDialog: typeof import('./src/components/StopSchedulesDialog.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TimeRangeInput: typeof import('./src/components/TimeRangeInput.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
