/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executors/': RouteRecordInfo<
      '/executors/',
      '/executors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executors/[id]': RouteRecordInfo<
      '/executors/[id]',
      '/executors/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/job-types/': RouteRecordInfo<
      '/job-types/',
      '/job-types',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/job-types/[id]': RouteRecordInfo<
      '/job-types/[id]',
      '/job-types/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/[id]': RouteRecordInfo<
      '/jobs/[id]',
      '/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/jobs/new': RouteRecordInfo<
      '/jobs/new',
      '/jobs/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance': RouteRecordInfo<
      '/maintenance',
      '/maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedules/': RouteRecordInfo<
      '/schedules/',
      '/schedules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/schedules/[id]': RouteRecordInfo<
      '/schedules/[id]',
      '/schedules/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/schedules/new': RouteRecordInfo<
      '/schedules/new',
      '/schedules/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/executors/index.vue': {
      routes:
        | '/executors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/executors/[id].vue': {
      routes:
        | '/executors/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/job-types/index.vue': {
      routes:
        | '/job-types/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/job-types/[id].vue': {
      routes:
        | '/job-types/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/jobs/index.vue': {
      routes:
        | '/jobs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/jobs/[id].vue': {
      routes:
        | '/jobs/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/jobs/new.vue': {
      routes:
        | '/jobs/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/maintenance.vue': {
      routes:
        | '/maintenance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/schedules/index.vue': {
      routes:
        | '/schedules/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/schedules/[id].vue': {
      routes:
        | '/schedules/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/views/schedules/new.vue': {
      routes:
        | '/schedules/new'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
