name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v6

    - uses: actions/setup-node@v7
      with:
        cache: "pnpm"

    - name: UI Build
      run: cargo xtask ui build

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
